### ISSUE TITLE
Question about packer and XCP-NG

### ISSUE THREAD

**Issue by jothoma1** [mtcoffee/xcp-ng-packer-examples#1]
First thanks for sharing your examples !
I start to use XCP-NG and would like to continue with packer (i already use it with VMware)
When trying your examples, i try a simple packer build and i have a crash :
panic: ConfigSpec failed: gob: type cty.Type has no exported fields [recovered] panic: ConfigSpec failed: gob: type cty.Type has no exported fields

I have tried on a Windows machine with packer 1.8.4 and on linux with the latest packer release and it's the same
Don't know where to start if you have an idea ?
thanks

**Comment by mtcoffee** [comment]
@jothoma1 
Have you tried with the current packer release? Version: 1.11.0

**Comment by jothoma1** [comment]
@mtcoffee yes i have tried with the current 1.11.0 but same crash

**Comment by mtcoffee** [comment]
Thanks @jothoma1 for pointing this out. Closing as the issue will be tracked in https://github.com/ddelnano/packer-plugin-xenserver/issues/140

**Comment by jothoma1** [comment]
Thanks !
